# Ch02/02_03

Python lists support slicing. Here's an example. Nums is a list of 1,2,3,4,5 and we do a slice from 2 to 4. It's going to run it. We're going to get 3 and 4. We start with the index 2 and index 3 and up two, but not including index 4.

In [2]:
nums = [1, 2, 3, 4, 5]
nums[2:4]

[3, 4]

These are half open ranges. You can do the same for Numpy arrays, so we create a vector with a range and then get a slice of this vector. Matrix slicing is useful since many times you'd like to take a subset of your data for training, testing, and other tasks.

In [3]:
import numpy as np

v = np.arange(1, 5)
v[2:4]

array([3, 4])

Numpy takes slicing to a whole new level. Let's have a look. Let's create an array with three rows and four columns.

In [4]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

When we take the array at location 0, we are going to get the 1st row.

In [5]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
arr

arr[0]

array([0, 1, 2, 3])

We can also say the second element in the 2nd row and this is 5 .

In [7]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
arr[1,1]

np.int32(5)

What happens if you want a column? We're going to use slicing. Say we want all the rows, but only the second element for every row, and now we're going to get 1, 5 and 9, which is the first column. Note that we get a flat array and not an array of ones.

In [9]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr[:,1]

array([1, 5, 9])

If you want to get the full array of ones you will need to reshape.So now we get it in a vertical format.

In [11]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
arr[:,1]

array([1, 5, 9])

In [13]:
arr[:,1].reshape((3, 1))

array([[1],
       [5],
       [9]])

You can do slicing on both axes, so all the rows from the 2nd row and the columns from the third column.

In [14]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
arr[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

You can also use slicing to set values, so I'm doing the slicing as before, but now equals 7 and now when I'm looking at the array I'm seeing that the bottom right is all 7.