Let's start looking into Numpy arrays. So first we import Numpy as np. And now I'm creating an array of three elements with 1, 2 and 3 run this. And we have an array 1, 2 and for starts. Arrays look very much like lists.

In [1]:
import numpy as np

arr = np.array([1,2,3])

print( arr )

[1 2 3]


So we can ask for the length.

In [2]:
import numpy as np

arr = np.array([1,2,3])

len(arr)

3

We can get the second element and arrays are 0 based indexing like the rest of Python.

In [3]:
import numpy as np

arr = np.array([1,2,3])

print( arr[1] )

2


But if you look closer, for example type of the 1st element, we see that it's not a Python integer but a Numpy int32.

In [4]:
import numpy as np

arr = np.array([1,2,3])

print( type ( arr[1] ) )

<class 'numpy.int32'>


For you can ask array what is the data type of the array using the dtype attribute. When you create an array, Numpy will determine the default type for the array for the input. However, you can specify explicitly the data type of the array to be created. This here is saying dtype np.int32 and we're going to get an array of int 32 comparing to any 64. This takes half the memory, but you need to make sure that all of your values fits inside a 32 bit integer.

In [5]:
import numpy as np

arr32 = np.array([1,2,3], dtype=np.int32)
arr32.dtype

dtype('int32')

You can multiply an array by itself. And what you're going to get is an elementwise multiplication, so 1 * 1 = 1, 2 * 2 = 4 and 3 * 3 = 9. I talked about Numpy and being fast. Let's have a look.

In [6]:
import numpy as np

arr = np.array([1,2,3])
arr * arr

array([1, 4, 9])

So I'm creating 2 arrays, each one with 1,000,000 random elements which are floats, and then I'm going to use the time magic to see how much time it takes. To multiply them and that took 6.27 milliseconds.

In [7]:
import numpy as np

v1 = np.random.rand(1_000_000)
v2 = np.random.rand(1_000_000)
%time v1 * v2

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 6 ms


array([0.20393425, 0.59213501, 0.19815701, ..., 0.2146252 , 0.0389571 ,
       0.07216258])

If you'd like to get the Dot Product of a matrix. Use the @ sign, which is the Python matrix multiplication operator. If we want to sell now, we're going to see 14, which is a dot product of these two arrays, we can move to more dimensions. So here's an array with three rows and three columns, and we can run this one. And now we can see the. That's a lot of code to write for a small sample metrics.

In [8]:
import numpy as np

arr = np.array([1, 2, 3])

arr @ arr

np.int32(14)

# NOTE (calculate the Dot Product)

arr @ arr = [1,2,3] @ [1,2,3] = [1, 4, 9 ] =

1 + 4 + 9 =

14